package health.hub.Enums;

public enum Wilaya {
    HODH_CHARGUI,
    HODH_EL_GHARBI,
    ASSABA,
    GORGOL,
    BRAKNA,
    TRARZA,
    ADRAR,
    DAKHLET_NOUADHIBOU,
    TAGANT,
    GUIDIMAGHA,
    TIRIS_ZEMMOUR,
    INCHIRI,
    NOUAKCHOTT_OUEST,
    NOUAKCHOTT_NORD,
    NOUAKCHOTT_SUD;
}
